#!/usr/bin/env python3
"""Generate font metrics from the online version of Adobe's 14 PDF core fonts."""
import re
import urllib.request
from io import BytesIO
from typing import Dict, List, Tuple
from zipfile import ZipFile

from pypdf._codecs import adobe_glyphs

# Original license:
license = """# The information contained in this file is based on the 14 PostScript(R)
# AFM files. This notice and the information contained in the FONT_METRICS
# dicionary were generated by the get_core_fontmetrics.py script in resources/
# All other content was added separately.
#
# Original license:
#
# This file and the 14 PostScript(R) AFM files it accompanies may be used,
# copied, and distributed for any purpose and without charge, with or
# without modification, provided that all copyright notices are retained;
# that the AFM files are not distributed without this file; that all
# modifications to this file or any of the AFM files are prominently
# noted in the modified file(s); and that this paragraph is not modified.
# Adobe Systems has no responsibility or obligation to support the use of
# the AFM files.
#"""


font_url="download.macromedia.com/pub/developer/opentype/tech-notes/Core14_AFMs.zip"
font_metrics : Dict[str, Tuple[Dict[str, object], Dict[int, Tuple[str, int]]]] = {}
font_files : List[str] = []
font_file_names = ("Courier.afm",
                   "Courier-Bold.afm",
                   "Courier-BoldOblique.afm",
                   "Courier-Oblique.afm",
                   "Helvetica.afm",
                   "Helvetica-Bold.afm",
                   "Helvetica-BoldOblique.afm",
                   "Helvetica-Oblique.afm",
                   "Symbol.afm",
                   "Times-Bold.afm",
                   "Times-BoldItalic.afm",
                   "Times-Italic.afm",
                   "Times-Roman.afm",
                   "ZapfDingbats.afm")


def get_fonts(font_url: str) -> List[str]:
    """
    Reads the Core14_AFMs.zip file and drops its contents into
    a list of "files".

    Returns:
        List of font "files"
    """
    with urllib.request.urlopen("https://" + font_url) as file_url, ZipFile(BytesIO(file_url.read())) as font_zip:
        for afm_font in font_zip.namelist():
            if afm_font in font_file_names:
                with font_zip.open(afm_font) as afm_font_file:
                    font_files.append(afm_font_file.read().decode())
    return (font_files)


def gen_font_db(
        font_files: List[str], license: str
    ) -> Tuple[Dict[str, Tuple[Dict[str, object], Dict[int, Tuple[str, int]]]], str]:
    """
    Reads a list with the contents of afm files and parses the files
    to get font descriptors and widths and copyright information.

    Returns:
        Font metrics
    """
    for file in font_files:
        for line in file.splitlines():
            f = line.strip().split(" ")
            if not f:
                continue
            k = f[0]
            if k == "FontName":
                fontname = f[1]
                props = {"FontName": fontname, "Flags": 0}
                chars: Dict[int, Tuple[str, int]] = {}
                font_metrics[fontname] = (props, chars)
            elif k == "C":
                width = int(f[4])
                glyph = adobe_glyphs[f"/{f[7]}"]
                char_ord = ord(glyph)
                char = glyph.encode("unicode_escape")
                chars[char_ord] = (char.decode(), width)
            elif k in ("CapHeight", "XHeight", "ItalicAngle", "Ascender", "Descender"):
                k = {"Ascender": "Ascent", "Descender": "Descent"}.get(k, k)
                props[k] = float(f[1])
            elif k in ("FontName", "FamilyName", "Weight"):
                k = {"FamilyName": "FontFamily", "Weight": "FontWeight"}.get(k, k)
                props[k] = f[1]
            elif k == "IsFixedPitch":
                if f[1].lower() == "true":
                    props["Flags"] = 64
            elif k == "FontBBox":
                props[k] = tuple(map(float, f[1:5]))
            elif k == "Notice":
                copyright = (" ".join(f[1:]))
                copyright = re.sub(r"Reserved.(.+)$", r"Reserved.\n# \1", copyright, flags=re.DOTALL)
                license = license + f"\n# {fontname}:\n# {copyright}\n#"

    return font_metrics, license


#ruff: noqa: T201
def print_font_metrics(
        fonts_metrics: Dict[str, Tuple[Dict[str, object], Dict[int, Tuple[str, int]]]],
        license: str
    ) -> None:
    """Prints font metrics to stdout in the form of a readable python dict."""
    print(license)
    print("\n\nFONT_METRICS = {")
    for fontname, (props, chars) in font_metrics.items():
        props_items_str = []
        for prop_key, prop_val in props.items():
            if type(prop_val) is str:
                d = '"'
            else:
                d = ""
            props_items_str.append(f'"{prop_key}": {d}{prop_val}{d}')
        props_str = "        {\n            " + ",\n            ".join(props_items_str) + ",\n        },"
        chars_items_str = []
        chars = dict(sorted(chars.items()))
        for k in chars:
            char_key, char_width = chars[k]
            d = '"'
            try:
                if ord(char_key) == 34:
                    d = "'"
            except TypeError:
                pass
            chars_items_str.append(f"{d}{char_key}{d}: {char_width}")
        chars_str = "        {\n            " + ",\n            ".join(chars_items_str) + ",\n        },"
        print(f'    "{fontname}": (\n{props_str}\n{chars_str}\n    ),')
    print("}")


if __name__ == "__main__":
    font_files = get_fonts(font_url)
    font_metrics, license = gen_font_db(font_files, license)
    print_font_metrics(font_metrics, license)
