#!/usr/bin/env python3
"""Generate PM/QA KYA markdown for pull request comments."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from common import PROJECT_ROOT  # noqa: E402


def changed_files(base_ref: str) -> list[Path]:
    result = subprocess.run(
        ["git", "diff", "--name-only", "--diff-filter=ACMR", f"{base_ref}...HEAD"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        result = subprocess.run(
            ["git", "diff", "--name-only", "--diff-filter=ACMR", "HEAD"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
    paths = [Path(line.strip()) for line in result.stdout.splitlines() if line.strip()]
    return [path for path in paths if path.exists()]


def _summarize_scope(files: list[Path]) -> str:
    if not files:
        return "No tracked file changes detected."
    customer_files = [path for path in files if not str(path).startswith((".newbie/", "scripts/", ".cursor/", "store/", "tests/chunk/"))]
    if customer_files:
        sample = ", ".join(str(path) for path in customer_files[:5])
        suffix = "..." if len(customer_files) > 5 else ""
        return f"Customer deliverables touched ({len(customer_files)} files): {sample}{suffix}"
    return f"Infrastructure/scaffold changes ({len(files)} files)."


def build_comment(files: list[Path]) -> str:
    scope = _summarize_scope(files)
    file_rows = "\n".join(f"| {path} | changed | review behavior |" for path in files[:12])
    if len(files) > 12:
        file_rows += f"\n| ... | +{len(files) - 12} more | |"

    return f"""<!-- nb-kya-autogen -->
## Newbie cross-functional summary

{scope}

### PM — acceptance criteria (draft)

1. Changed behavior is documented in the PR description and matches the stated user intent.
2. Any new customer code under the configured workspace uses only indexed public library APIs.
3. Local index health passes: `python scripts/doctor.py`.
4. Symbol gate passes: `python scripts/verify_symbols.py --git-diff`.

### QA — test cases (draft)

| ID | Scenario | Steps | Expected |
| --- | --- | --- | --- |
| QA-1 | Happy path | Exercise the primary workflow changed in this PR | Expected output matches acceptance criteria |
| QA-2 | Regression | Run existing tests for touched modules | No new failures |
| QA-3 | Symbol boundary | `python scripts/verify_symbols.py --git-diff` | Pass — no private/hallucinated imports |
| QA-4 | Index grounding | `python scripts/query.py --library <lib> --prompt \"<intent>\"` on affected APIs | Retrieved chunks support the implementation |

### Files changed

| Path | Change | Notes |
| --- | --- | --- |
{file_rows if file_rows else "| (none) | | |"}

---
*Auto-generated by `scripts/pr_kya_comment.py`. Edit the PR description or comment to refine.*
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Build KYA markdown for PR comments.")
    parser.add_argument("--base-ref", default="main")
    parser.add_argument("--json", action="store_true", dest="json_output")
    args = parser.parse_args()

    files = changed_files(args.base_ref)
    comment = build_comment(files)
    if args.json_output:
        print(json.dumps({"files": [str(path) for path in files], "comment": comment}, indent=2))
        return
    print(comment)


if __name__ == "__main__":
    main()
