name: 'GitHub Pages Check'
on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  url-check:
    name: GitHub Pages check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Pages
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          ref: 'gh-pages'
          path: 'gh-pages'
          persist-credentials: false
      - name: Checkout main (tools)
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          ref: main
          path: main
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1  # v6.3.0
        with:
          python-version: '3.x'
      - name: Check GitHub Pages
        run: |
          export PYTHONPATH="$GITHUB_WORKSPACE"
          python main/.github/scripts/check_gh_pages_updates.py
