name: 'URL Check'
on:
  workflow_dispatch:
  schedule:
    - cron: 0 6 * * 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  url-check:
    name: URL check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: '3.x'
      - name: Install requirements
        run:
          pip install pyyaml Pillow
      - name: Check URLs
        run: |
          export PYTHONPATH="$GITHUB_WORKSPACE"
          python .github/scripts/check_urls.py
